; PlatformIO Project Configuration File
; KARIM Car Controller - ESP32
;
; Build Options:
;   pio run                   → compilar
;   pio run --target upload   → subir por USB
;   pio run --target upload --upload-port <IP>  → subir por OTA
;
; Monitor:
;   pio device monitor

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Monitor
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; OTA serial
upload_protocol = esptool

; Librerías
lib_deps =
    ;

; Opciones de compilación
build_flags =
    -D CORE_DEBUG_LEVEL=1
